# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Scoring
SCORE_TICK_COOLDOWN = 0.5
SCORE_TICK_AMOUNT = 1
ASTEROID_SCORE_FACTOR = 3

# Asteroid behavior
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2.5 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player behavior
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 200
PLAYER_MAX_SPEED = 200
PLAYER_ACCELERATION = 300
PLAYER_START_LIVES = 3

# Shot behavior
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

# Collectibles
COLLECTIBLE_SHIELD_LIFETIME = 10
COLLECTIBLE_SPEED_LIFETIME = 10
SPEED_EFFECT_DURATION = 4
